- pyccl/power.py
Change from Mpc^{-3} to Mpc^3. This relates to issue #245.
> Fix power spectrum units in power.py

- src/ccl_neutrinos.c
This pull request fixes a bug where a spline was still being called in the high and low limits of mnu / T (where it was not defined), because the limiting values were not being returned, only calculated then discarded.
This should hopefully address issue #251
> Fix bug in limits of neutrino integral

- README.md
The example code in the README file assumes an older version of the Python wrapper, and fails with the current version. This PR fixes the issue.
> Fix bug in example Python code in README file

- .travis.yml
I just noted that travis only covered 2.7, so I quickly added 3.5 and 3.6. Checks out [just fine](https://travis-ci.org/DanielLenz/CCL), no issues.
> Add python 3 to travis

- pyccl/cls.py
- pyccl/core.py
- pyccl/correlation.py
- pyccl/pyutils.py
- src/ccl_massfunc.c
Fixes issue #262 - the default mass function prescription is Tinker2008, but the halo bias is only defined for Tinker2010. The error function in this case is not helpful at all, so it'd be nice to change the current error handling system to output the actual error message raised at the C library level (probably in a different PR to avoid mission creep)
> fix consistency with default mass function prescription

- include/ccl_lsst_specs.h
This is a one-line change in the docs of ccl_lsst_specs.h. It is a trivial commit to be merged to master so we can check whether readthedocs integration has been successful.
> Trivial doc change to test readthedocs

- tests/ccl_sample_run.c
This is a small fix to ccl_sample_run.c that solves a bug where we were calling the galaxy lensing tracer instead of the CMB lensing tracer. This refers to issue #315.
> Fix issue 315

- doc/0000-ccl_note/Makefile
Myself and other people have been having problems with `mkauthlist` always trying to change the `numpy` version through pip and other annoyances.
This PR:
- Adds test in Makefile to see if `mkauthlist` command exists, instead of just trying to `pip upgrade` it every time we run `make`.
- Allows the user to manually specify the path to the `mkauthlist` command themselves, by setting the `MKAUTHLIST` environment variable.
Example usage:
```sh
$ make
Makefile:107: *** "mkauthlist not found. Install using 'pip install mkauthlist'". Stop.
```
```sh
$ MKAUTHLIST=/home/mariecurie/.local/bin/mkauthlist make
<makefile runs>
```
> Fix issue with `pip` always trying to reinstall `mkauthlist` dependencies

- pyccl/pyutils.py
Fixes issue #324, crashes caused by improper handling of integer arguments.
> Do type check for integers in Python wrapper, to prevent crashes

- src/ccl_error.c
Protect against killing the Python interpreter by using `ccl_raise_exception()` instead of `exit()` statements in `ccl_check_status_nocosmo()`.
> Guard against errors that would kill the Python interpreter

- CMakeLists.txt
- tests/readme.md
This PR fixes the CMakeLists file to incorporate some tests that were missing. This brings the lists of tests back to 62 (from 40 in current master).
> Bring back missing tests

- src/ccl_cls.c
This new PR is meant to replace #353 with a version of the fix compatible with current master.
It still fixes #302 (the script submitted by Joe still fails without it) and now outputs a warning message if the native integration function has to use  the backup `cquad` integration function.
> Adds backup integration function for computing Cls

- .travis.yml
- .travis/install.sh
- CMakeLists.txt
- cmake/Modules/BuildCLASS.cmake
- cmake/class-2.6.3.patch
- pyccl/__init__.py
- setup.py
As documented in #411 there were some unforeseen consequences to the pip install process (entirely my fault btw). Contrary to CCL, CLASS is not a proper package in the sense that it is not meant to be compiled then installed in a different directory, it relies on hard coded file path pointing to the compile directory. 
Problem is that pip build the package in a temporary directory, then install the package in a different location and removes the temporary, so class can't find data files needed by the big bang nucleosynthesis  and recombination modules.
So, here is my proposal to solve this problem.
The C library needs to be movable for pip, there is no way around that, so I adopt the same strategy than in CCL to provide the file paths, which is to first check an environment variable, then …
> Solves problem with pip install breaking CLASS

- pyccl/CMakeLists.txt
This PR fixes #434 by updating the way the dependencies are specified for the SWIG targets. Long story short, the python wrapper target generated by swig is not covered by `add_dependencies(${SWIG_MODULE_ccllib_REAL_NAME} SWIG)`.
> Fixes the dependencies in SWIG build

- pyccl/CMakeLists.txt
Removing an option that sets the naming convention for SWIG, and which was apparently broken in the latest release 3.12 or cmake. Closes #455
> Removes SWIG naming option

- examples/Lensing angular power spectrum.ipynb
This PR fixes the typo in the notebook. Closes #425
> BUG fix lensing C(ell) notebook typo

- CONTRIBUTING.md
This is a small PR to add details on flake8 to the CONTRIBUTING file. flake8 is now part of our Travis tests and developers should run it together with tests of the library.
> Add flake8 to CONTRIBUTING

- pyccl/cls.py
- pyccl/core.py
- pyccl/correlation.py
- pyccl/pyutils.py
- tests/ccl_test_core.py
This PR changes the code to raise an error if the C cosmology object is being used. 
Closes #475
> ENH raise an error if a C ccl cosmology object is passed

- cmake/Modules/BuildAngpow.cmake
- cmake/Modules/BuildCLASS.cmake
When building CCL from scratch, the cloning into CLASS stage tends to take a while. This PR attempts to address this by passing `GIT_SHALLOW` to cmake for CLASS and Angpow. Anecdotally, this speeds up the installation by quite a bit.
> Shallow git clone when getting CLASS and Angpow

- cmake/Modules/BuildAngpow.cmake
- cmake/Modules/BuildCLASS.cmake
- tests/ccl_test_emu.c
- tests/ccl_test_emu_nu.c
This branch enables the previously commented-out tests for the cosmic emulator power spectra. This is a fall back option in case we don't manage to get flags for the tests this week (#498). I think we should merge this for now.
> Enable missing tests

- CONTRIBUTING.md
This is a small PR that adds some minimal guidelines on how to comprehensively incorporate benchmarks for a new feature in CCL.
> Minimal guidelines for adding benchmarks

- cmake/Modules/BuildAngpow.cmake
- cmake/Modules/BuildCLASS.cmake
Using `GIT_SHALLOW` in `ExternalProject_Add` makes the cloning a lot faster but seems to break for older cmake versions. This PR attempts to address that. 
Requires testing from people with old cmake versions!
> Disable GIT_SHALLOW for cmake < 3.10.

- cmake/Modules/FindNumPy.cmake
Quote fourth parameter to allow build on macOS with a MacPorts build environment. 
Similar to https://github.com/facebook/rocksdb/pull/1231/commits/5254c85fe27deed13c075fb7906eb674084b10c3.
> Quote fourth parameter of string(REGEX REPLACE ... ) to allow build on macOS

- src/ccl_power.c
Right now CCL doesn't free up all the memory initialized by class. This is about 7MB for each call, which is extremely hurtful for any MCMC.
This PR fixes this, but I'm worried that the restructuring of all of our `free`s after the code review may have introduced other similar bugs, so we should run valgrind on a few typical use cases.
> fixed class memory leak

- pyccl/CMakeLists.txt
- setup.py
This PR aims fixes #541 .  So far, pyccl was compiled for the default python interpreter found in the environment. In some cases, one may want to compile pyccl for a different version, like :
```
$ python2 setup.py build
```
when python3 is the default interpreter. 
With this PR, CMake will accept a new command line option `PYTHON_VERSION` which is used internally when looking for the python interpreter. This could be used in a call to cmake like so:
```
$ cmake .. -DPYTHON_VERSION=2
```
but in practice, the setup.py will take care of providing this option. So, all that is needed is to run `python2 setup.py build` like before.
> Compiles CCL for version of  python used to call pip or setup.py

- CHANGELOG.md
- src/ccl_power.c
This PR fixes the power spectrum bug eval at zero for the v1.0 branch.
> BUG eval power spectrum near zero better v1.0

- CHANGELOG.md
- src/ccl_power.c
This PR fixes the memory leak on the v1.0 release branch in addition to master. 
Closes #547
> BUG mem leak in power spectrum for v1.0

- CHANGELOG.md
- src/ccl_correlation.c
This PR fixes some pretty bad memory leaks in this function. 
Closes #568
> BUG fix memory leaks in correlation function routines

- README.md
- TERMS.md
Adds the terms of reference discussed in the telecons and the Slack channel.
> CCL terms of reference

- src/ccl_tracers.c
Currently CCL figures out automatically what range of radial distances it should use to calculate power spectrum. This works fine as long as all radial kernels are positive, but this is not always the case (e.g. magnification). This is an uber-quick fix.
> Kernel edges

- src/ccl_core.c
I was working on getting us into conda-forge and their compilers found this bug.
> BUG cannot have `va` stuff in critical section for some compilers

- CHANGELOG.md
- MANIFEST.in
This PR adds some extra files to the sdist in order to fix the PyPi release. IDK how we did not catch this before. :/
> BUG fix PyPi release by adding extra files to the sdist

- CHANGELOG.md
- benchmarks/test_cls.py
- include/ccl_cls.h
- include/ccl_core.h
- include/ccl_utils.h
- pyccl/ccl_cls.i
- pyccl/cls.py
- pyccl/pyutils.py
- pyccl/tests/test_cls.py
- pyccl/tests/test_swig_interface.py
- src/ccl_cls.c
- src/ccl_core.c
- src/ccl_haloprofile.c
- src/ccl_utils.c
This branch:
- Defines a spline integrator function at the C level
- Allows the user to switch to it (instead of using the default GSL integrator)
Three reasons for this:
- Spline integrals are potentially faster and not much less accurate than GSL's quad.
- They won't fail, which can be convenient (they may just give you a less accurate answer).
- I need this type of integration for the halo model power spectrum branch.
> Spline integral

- pyccl/nl_pt/power.py
- readthedocs/source/developer_installation.rst
- readthedocs/source/installation.rst
Added notes on how to install `Fast-PT` to docs, as well as the error message when `Fast-PT` is missing.
> Add Fast-PT installation guide to docs

- include/ccl_core.h
- pyccl/ccl_core.i
- pyccl/tests/test_spline_params.py
- src/ccl_background.c
- src/ccl_core.c
This is a cleaner implementation of PR #748 . On the C-level, it makes `A_SPLINE_MAX` a const and checks its value in `ccl_cosmology_create`. On the Python-level it overwrites the setter to throw a `RuntimeError` with an informative error message.
I think the only way to bypass these checks is to create a new `ccl_spline_params` struct with  A_SPLINE_MAX != 1 and replace the `spline_params` in an existing `ccl_cosmology` struct. If a user goes that far, they can probably break other things just as easily.
> Make A_SPLINE_MAX functionally a constant

- benchmarks/test_camb_class_consistent.py
- benchmarks/test_correlation_MG2.py
- benchmarks/test_haloprofile.py
- benchmarks/test_power_nu.py
- include/ccl_core.h
- pyccl/correlation.py
- pyccl/halos/halo_model.py
- pyccl/pyutils.py
- pyccl/tests/test_cclerror.py
- pyccl/tests/test_cls.py
- pyccl/tests/test_correlation.py
- pyccl/tests/test_halomodel.py
- pyccl/tests/test_haloprofile.py
- pyccl/tests/test_massfunction.py
- pyccl/tests/test_mg.py
- pyccl/tests/test_power.py
- pyccl/tests/test_power_mu_sigma_sigma8norm.py
- pyccl/tests/test_profiles.py
- pyccl/tracers.py
- src/ccl_background.c
- src/ccl_f2d.c
While helping Elisa and Mustapha try to find their problems running the test suite on master, I noticed that you currently have a lot of warnings show up both when compiling and when running the tests.  IMO, it's a good idea to try to remove all these warnings.  So I went ahead and did so for you.
At least 3 of the compiler warnings were actual bugs (related to runtime failures, so didn't affect much in normal operations).  
The python warnings were mostly CCL deprecations, so for these I added a test using assert_warns to check that the deprecation warning was raised, and to catch it from being output to the terminal.
Finally, there were a couple other warnings related to numpy and collections that aren't a problem yet, but might become a problem in the future.  So worth fixing now …
> Remove warnings for v2.1

- readthedocs/source/installation.rst
Adding instructions to read the docs on how to install ISiTGR via pip or conda to use with CCL
> adding instructions to readthedocs for isitgr installation

- .travis.yml
- readthedocs/source/development_workflow.rst
This PR aims to have travis automatically upload the source distribution for CCL to PyPi on new releases without manual intervention. I have encoded an access token for pypi, and this should work, but can't really test it until the next release.
This should fix #774
> Adding automated travis upload to PyPi

- pyccl/core.py
- pyccl/tests/test_background.py
- pyccl/tests/test_power.py
This PR allows CCL to take in growth from input arrays independently from the background. This is convenient because CAMB/CLASS actually do not provide those quantities in a nice manner (because they are actually not well defined in general).
In doing this I've also fixed a bug with how the linear and non-linear power spectra were being taken from input arrays.
> Growth from arrays

- pyccl/core.py
The linear growth needs to be initialized with the linear power spectrum, since it is needed when extrapolating it at high redshifts.
Closes #859
> Initialize growth in cosmology calculator

- CHANGELOG.md
- include/ccl_config.h
- pyccl/boltzmann.py
- pyccl/core.py
- pyccl/tests/test_nonlin_camb_power.py
Redo of PR #837. Much simpler thanks to David's calculator mode and yaml handling in python.
Currently CCL only uses the linear power spectrum prediction from Boltzmann codes, with limited options for nonlinear power spectra. Boltzmann codes provide a range of fast nonlinear models that can be used. For example, CAMB provides an extensive list of codes, among them HMCode.
This PR uses the HMCode implementations in CAMB to provide nonlinear predictions for the matter power spectrum, including modelling of baryons, for CCL. It addresses issue #819.  
The nonlinear power spectra are accessed by setting `matter_power_spectrum="camb"`. To specify parameters, I added a generic `extra_parameters` kwarg to `Cosmology.__init__`. This is meant to take a dictionary and act as a catch-all for more …
> Expose nonlinear CAMB power spectra

- pyccl/ccl_tk3d.i
- pyccl/tests/test_tk3d.py
`Tk3D.__del__` calls `lib.f3d_t_free`, which however isn't exposed. In other, words a memory leak. Since this happens in `__del__` the `AttributeError` exception that is raised is usually ignored. It's not entirely clear to me why this isn't at least reported as a warning when pytest runs though. Maybe something funny about when `__del__` is called when going out of scope.
This should be fixed by including the relevant header file in `ccl_tk3d.i`.
> Fix AttributeError in Tk3D.__del__

- pyccl/boltzmann.py
- pyccl/core.py
- pyccl/tests/test_power.py
I included an option to choose which type of dark energy you want when using camb. It defaults to "fluid", now one can easily set it to "ppf".
I simply set "self._params.DE_model_camb = DE_model_camb" because I was having a difficult time with the C files.
> Camb dark energy model

- pyccl/halos/__init__.py
- pyccl/halos/profiles_2pt.py
- pyccl/tests/test_profiles.py
Cont. work from #874 . Basically, a parameter `r_corr` which controls the sign of the correlation of two profiles, which do not necessarily have to be fully correlated.
In the original implementation I subclassed `Profile2pt` into `Profile2ptR`, because there was an explicit statement to only subclass `Profile2pt` for more complicated 2-point moments, but in hindsight, there is no reason for this prohibition to exist. So I am implementing it directly into the base class.
> Tuning knob param for 1-halo 2-point correlations

- pyccl/__init__.py
- pyccl/core.py
- pyccl/halos/__init__.py
- pyccl/tests/test_cosmology.py
I have added few lines of code to `core.py` to make (almost) all of the `pyccl` functions which accept `cosmo` as their first argument, methods of the `Cosmology` class.
1. **pyccl.background**
- growth_factor
- growth_factor_unnorm
- growth_rate
- comoving_radial_distance
- comoving_angular_distance
- angular_diameter_distance
- luminosity_distance
- h_over_h0
- distance_modulus
- scale_factor_of_chi
- omega_x
- rho_x
2. **pyccl.bcm**
- bcm_model_fka
- bcm_correct_pk2d
3. **pyccl.boltzmann**
- get_camb_pk_lin
- get_isitgr_pk_lin
- get_class_pk_lin
4. **pyccl.cls**
- angular_cl
5. **pyccl.correlations**
- correlation
- correlation_3d
- correlation_multipole
- correlation_3dRsd
- correlation_3dRsd_avgmu
- correlation_pi_sigma
6. **pyccl.covariances**
- angular_cl_cov_cNG
7. **pyccl.pk2d** …
> Methods of Cosmology

- pyccl/core.py
- pyccl/tests/test_nonlin_camb_power.py
The docs suggest that `halofit_version=mead2020` accounts for baryon feedback, but that should be `mead2020_feedback`.
This also fixes the tests to get the agreement with CAMB to O(1e-5) by using the same setup as in `boltzmann.py` (namely setting T_CMB and using the same k-range).
> Update docs and tests to use mead2020_feedback.

- pyccl/boltzmann.py
- pyccl/covariances.py
- pyccl/halos/concentration.py
- pyccl/halos/halo_model.py
- pyccl/halos/hbias.py
- pyccl/halos/hmfunc.py
- pyccl/halos/massdef.py
- pyccl/halos/profiles.py
- pyccl/nl_pt/power.py
- pyccl/pk2d.py
- pyccl/power.py
- pyccl/tests/test_tracers.py
- pyccl/tracers.py
This catches the case where the tracer redshift support is wider than the interal background spline. This is mostly useful to prevent opaque error in calculator mode. A similar check should probably be made for the power spectrum as well.
> Make tracer spline errors more verbose

- CMakeLists.txt
- readthedocs/source/developer_installation.rst
- setup.py
This adds the `--debug` option to enable debug builds. Also adds the `clean` command to remove `pyccl/_ccllib.so` (not removing that can cause very obscure crashes) and `build`.
Also enables openmp on macOS clang.
> Option to compile CCL with debugging symbols

- src/ccl_core.c
`ccl_cosmology_set_status_message` checks if `cosmo->status_message` is empty, i.e a 0-length string. If `cosmo->status_message` is initially garbage, that check triggers the warning about overwriting an existing message and prints garbage. This PR explicitly initialises `cosmo->status_message` as a 0-length string.
> Fix status message string initialisation

- benchmarks/test_haloprofile.py
- pyccl/halos/profiles.py
In pyccl.halos.profiles, convergence, shear, reduced_shear and magnification can now handle array_like a_source.
> Fix WL functions in pyccl.halos.profiles

- pyccl/halos/profiles_cib.py
Using `numpy` broadcasting rules we can get at least a 10-fold speed increase (and up to 100x) in the computation of `_Lumsat` in `HaloProfileCIBShang12`, thus avoiding having to write this in C.
> 10x speed increase in CIB profile

- pyccl/halos/__init__.py
- pyccl/halos/halo_model.py
- pyccl/tests/test_tkkssc.py
As a first implementation in TJPCov, in order to avoid the user to have to define several halo model parameters, it might be useful to have an approximation of the SSC. What I have implemented here is `tkk_ssc ~ b1 * b2 * First_term_for_a_NFW_profile + (b1 * delta_1_nc + b2 * delta_2_nc) * Pmm_for_a_NFW_profile` (see Eq. A13 in 1601.05779), where `delta_1_nc = 1` if the first quantity is for number counts and 0 if not.
I have also fixed the docstring for the SSC trispectrum function.
> Super Sample Covariance with linear galaxy bias approximation

- .github/workflows/publish.yml
This adds a github action that automatically pushes the code to pypi whenever you create a release on Github.
The current version just pushes to the test version of pypi, so that we can see if everything is working before releasing to the real version. I'd suggest we do that as a first PR and then check it's all working and then a second PR to change it to use the real pypi.
To work this will need one of the maintainers of the PyPI project to create an upload token, by following these steps if they don't have one already.
- Log into test.pypi.org
- Click on your user name in the top right > Your Projects > Account Settings
- Scroll down to "API tokens". Click "Add API Token"
- Choose a sensible name like `CCL_UPLOAD_TOKEN`
- Under "scope", select pyccl from the drop-down menu
- Click "Add …
> Add action to publish to pypi

- pyccl/pk2d.py
- pyccl/tests/test_halofit_highz.py
This issue recently came up when people tried using the CCL halofit with wa != 0 cosmologies in calculator mode and caused unhelpful error messages. Specifically, halofit translates (w0, wa) to a w0_eff. This requires computing the comoving distance to the CMB, which requires the background splines being sampled to sufficiently high redshifts. This PR adds a check for this case and gives a more informative error message.
> Check for range of background splines when using halofit with wa != 0.

- pyccl/tests/test_tracers.py
- src/ccl_tracers.c
> Bug in magnification bias

- pyccl/tests/test_tracers.py
- pyccl/tracers.py
Closes #823 
This is actually documented, but at least now we'll throw a more useful error.
> Useful error for transfer functions with non-monotonic scale factors

- setup.py
As mentioned in #949 , `setuptools` won't work anymore because it requires py37+.
Python 3.6 is past its end of life so with this PR we stop supporting it and require that py37+ is used, in order to install CCL.
> Stop supporting Python 3.6

- pyccl/core.py
- pyccl/tests/test_nonlin_camb_power.py
Closes #978 . 
That was a very peculiar issue, and it has never popped up before because the only combination of `transfer_function` and `matter_power_spectrum` that would result in the non-linear power spectrum not being calculated would be `boltzmann_class` and `camb`. I guess no one has ever wanted to get the linear power spectrum through `CLASS`, but then query `CAMB` for the non-linear model. 
Seeing as in the future we might want to add other options for the linear power spectra, this ensures that the error won't show.
> Compute non-linear power spectrum for `(trf, mps) == (not camb, camb)` combinations.

- pyccl/halos/profiles.py
- pyccl/tests/test_profiles.py
The Einasto alpha parameter can now be assigned by users.
> Add option to make einasto alpha a free parameter

- pyccl/core.py
- pyccl/tests/test_cls.py
- pyccl/tracers.py
Closes #976 . MG tracers use `sigma_0` to compute the modified gravity factor for the transfer function. Just this parameter is needed, but I added `mu_0` as well for completeness. Might be good to think about whether it's worth also adding `c1_mg`, `c2_mg` and `lambda_mg`.
> MG parameters in `CosmologyCalculator`

- pyccl/nl_pt/power.py
- pyccl/tests/test_pt_power.py
This PR contains enhancement to the perturbative modelling in CCL to make its integration in firecrown easier.
- Allow skipping of calling `ptc.update_pk` in `get_pt_pk2d`
> Enhancement to the perturbative modelling

- pyccl/halos/halo_model.py
- pyccl/tests/test_halofit_highz.py
In #925 , I moved the `rho0` calculation inside of `get_ingredients` but forgot to include a check, so that `rho0` is re-computed every time `cosmo` changes. In essence, we didn't fix the problem in 925, we just moved it to a different method.
With this PR we now check for cosmo equality. There is no `__eq__` currently implemented in `Cosmology`, so Python falls back to id-checking (an okay assumption for now).
I moved `rho0` out of the if-statement (so it gets computed every time), or we'd have to carry out checks for every possible combination of (mass_function, halo_bias), (cached a, not cached, or None), (cached cosmo, not cached, or None), which would complicate things a lot.
I simplified the way we compute `rho0`, so that it doesn't call `rho_x` anymore, and so it doesn't have to …
> `HaloModelCalculator` check cosmo in `get_ingredients`.

- .github/environment.yml
- .github/workflows/ci.yml
Some years ago, when the Python package handling in CI was changed to `conda`, the Python version was still left as a specifier in the matrix. However, this doesn't do anything at all. Conda would just use Python 3.11 (the latest version) even though we had 3.8 specified.
[Proof](https://github.com/LSSTDESC/CCL/actions/runs/4437584140/jobs/7787479584) (build from `master`):
```
Package                 Version  Build                Channel                    Size
─────────────────────────────────────────────────────────────────────────────────────────────────
Install:
─────────────────────────────────────────────────────────────────────────────────────────────────
...
+ python                 3.11.0  he550d4f_1_cpython   conda-forge/linux-64       31MB
...
```
This PR moves the Python …
> Fix incorrect Python version in CI

- pyccl/parameters.py
- pyccl/tests/test_cosmology.py
- readthedocs/source/notation_and_other_cosmological_conventions.rst
Adds an option to unfreeze the physical constants, for users who want to set their own constants to match simulations etc.
Closes #1007.
> Unfreeze option for `physical_constants`

- benchmarks/test_distances.py
- include/ccl_core.h
- pyccl/__init__.py
- pyccl/ccl_core.i
- pyccl/core.py
- pyccl/neutrinos.py
- pyccl/parameters.py
- pyccl/tests/test_cclobject.py
- pyccl/tests/test_cosmology.py
- pyccl/tests/test_neutrinos.py
- pyccl/tests/test_parameters.py
- pyccl/tests/test_swig_interface.py
- src/ccl_background.c
- src/ccl_core.c
This one completely decouples `T_CMB` and `T_ncdm` from the physical constants.
It also exploits the `CCLParameters` framework that was there to make the C-level cosmological parameters communicate with Python, and port their setting-up to Python fully.
> Remove `T_CMB` and `T_ncdm` as constants (reloaded)

- README.md
- pyccl/base.py
- pyccl/core.py
- pyccl/halos/concentration.py
- pyccl/halos/halo_model.py
- pyccl/halos/hbias.py
- pyccl/halos/hmfunc.py
- pyccl/halos/massdef.py
- pyccl/halos/profiles.py
- pyccl/halos/profiles_2pt.py
- pyccl/halos/profiles_cib.py
- pyccl/parameters.py
- pyccl/pk2d.py
- pyccl/tests/test_cclobject.py
- pyccl/tests/test_concentration.py
- pyccl/tests/test_cosmology.py
- pyccl/tests/test_pk2d.py
- pyccl/tests/test_pkhm.py
- pyccl/tests/test_profiles.py
- pyccl/tests/test_tk3d.py
- pyccl/tests/test_tracers.py
- pyccl/tk3d.py
- pyccl/tracers.py
As @rmjarvis and @marcpaterno correctly pointed out, we can save loads of time comparing `CCLObjects` if we compare parameters instead of strings. To that end, I extended some functionality that was already there to do parameter comparisons for most objects.
Just like the `__repr_attrs__` class variable, which automatically builds a repr using a list of specified arguments, `__eq_attrs__` now makes sure that the default `__eq__` is overridden and that the individual attributes are compared one-by-one.
For example, in the `Cosmology` object, we only need to add this line in the beginning:
```python
__eq_attrs__ = ("_params_init_kwargs", "_config_init_kwargs", "_accuracy_params",)  # check these
def __init__(...):
...
```
There are only 3 classes where this is not possible (because we have …
> Implement separate `__eq__` methods

- pyccl/base/schema.py
- pyccl/halos/halo_model.py
- pyccl/halos/massdef.py
- pyccl/tests/test_cclobject.py
- pyccl/tests/test_massdef.py
- pyccl/tests/test_pkhm.py
This is a rebased copy of 1065.
I brought the extra stuff from 1064 to here, so that we keep the other PR as clean as possible, and this PR also defines a library-level control to turn on/off the custom `__eq__` methods, just as we had with the `__repr__` methods.
Old Description
--------------------
The main change this PR introduces, is to make `mass_def` an optional argument in `HMCalculator` because if `mass_function` and `halo_bias` are passed as instances (rather than str) we can just use their own `mass_def`. We can do that because some lines below we enforce that all `mass_def`s are equal.
So an `HMCalculator` can be instantiated in one of the following ways:
```python
hmc = ccl.halos.HMCalculator(mass_function="Tinker10", halo_bias="Tinker10", mass_def="200c")
mdef = …
```
> Additional halos features

- pyccl/base/schema.py
- pyccl/parameters.py
- pyccl/pk2d.py
- pyccl/tk3d.py
- pyccl/tracers.py
We didn't include this check in the beginning which would make comparison much faster for same-id objects.
> `self is other` shortcut for `__eq__`

- pyccl/base/deprecations.py
- pyccl/halos/__init__.py
- pyccl/halos/halo_model.py
- pyccl/halos/halo_model_base.py
- pyccl/halos/massdef.py
- pyccl/halos/pk_4pt.py
- pyccl/halos/profiles/einasto.py
- pyccl/halos/profiles/gaussian.py
- pyccl/halos/profiles/powerlaw.py
- pyccl/halos/profiles/pressure_gnfw.py
- pyccl/halos/profiles/profile_base.py
- pyccl/halos/profiles_2pt.py
- pyccl/neutrinos.py
- pyccl/tests/test_massdef.py
- pyccl/tests/test_v3_api.py
Currently `v3_wip` breaks the API. WIth this PR we preserve it for CCLv2.final. I ran the old tests with the new code and came up with a list of things that failed (because API was broken). This list should be complete now.
Bonus:
> Preserve API in v2.final

- pyccl/cosmology.py
- pyccl/halos/halo_model.py
- pyccl/halos/pk_1pt.py
- pyccl/halos/pk_2pt.py
- pyccl/halos/pk_4pt.py
- pyccl/pk2d.py
- pyccl/pyutils.py
- pyccl/tests/test_power.py
- pyccl/tests/test_tkkssc.py
The current version of the code implements the v3 API while attempting to preserve the v2 API. In this PR, I made a copy of the unit tests and benchmarks (not part of the PR) as they were before any of these modifications took place (in the latest released version, v2.7). I then ran the tests, which use the pure v2 API, and ensured that they pass.
In doing so, I weeded out a couple of bugs and restored some pieces of code that strictly speaking are part of the v2 API.
Now the caveats. Not all old tests passed, but the reasons behind those that didn't pass are all reasonable:
- Some function calls now raise errors with a different error type than in v2. The new error types are more appropriate, and hence this should be interpreted as a bugfix.
- Some function calls don't raise an error or …
> API restoration

- pyccl/halos/profiles/hernquist.py
- pyccl/halos/profiles/nfw.py
Use `np.arcsinh` and `np.arcsin` for numerical stability when `xx` is close to 1.
> Improve NFW and Hernquist `_fx_projected` and `_fx_cumul2d`

- include/ccl_massfunc.h
- pyccl/halos/concentration/__init__.py
- pyccl/halos/concentration/bhattacharya13.py
- pyccl/halos/concentration/diemer15.py
- pyccl/halos/concentration/ishiyama21.py
- pyccl/halos/halo_model_base.py
- pyccl/halos/hbias/__init__.py
- pyccl/halos/hbias/bhattacharya11.py
- pyccl/halos/hbias/sheth01.py
- pyccl/halos/hbias/sheth99.py
- pyccl/halos/hbias/tinker10.py
- pyccl/halos/hmfunc/__init__.py
- pyccl/halos/hmfunc/despali16.py
- pyccl/halos/hmfunc/press74.py
- pyccl/halos/hmfunc/sheth99.py
- pyccl/halos/hmfunc/tinker10.py
- pyccl/halos/profiles/einasto.py
- pyccl/tests/test_massfunction.py
- src/ccl_massfunc.c
This unifies the calculation of the linear spherical collapse threshold into a single function (also reducing the C-level API).
> Homogenise linear collapse threshold

- pyccl/cosmology.py
- pyccl/tests/test_baryons.py
- readthedocs/api/pyccl.emulators.cosmicemu_MTIV_pk.rst
This implements, as discussed in the last CCL telecon, the possibility to pass baryonic effects objects as part of the cosmology initialisation. This is a convenience feature, so users can just keep using Cosmology objects as containers for the non-linear matter power spectrum, which now can include baryonic effects.
> Baryons objects as convenience input for Cosmology

- benchmarks/test_correlation_MG.py
- benchmarks/test_correlation_MG2.py
- benchmarks/test_correlation_MG3_SD.py
- benchmarks/test_distances.py
- benchmarks/test_growth.py
- benchmarks/test_halomod_numbercounts.py
- benchmarks/test_power_mg.py
- benchmarks/test_power_mg2.py
- pyccl/boltzmann.py
- pyccl/cosmology.py
- pyccl/modified_gravity/__init__.py
- pyccl/modified_gravity/modified_gravity_base.py
- pyccl/modified_gravity/mu_Sigma.py
- pyccl/tests/test_baryons_vd19.py
- pyccl/tests/test_cells.py
- pyccl/tests/test_hmcalculator_number_counts.py
- pyccl/tests/test_mg.py
- pyccl/tests/test_power_mu_sigma_sigma8norm.py
This PR introduces a `ModifiedGravity` interface to the `Cosmology` class which encapsulates MG parametrisations (just mu-Sigma for now). Under the hood (i.e. C-layer) nothing has changed.
The motivation is to reduce clutter in the `Cosmology` interface and allow different MG parametrisations in the future without breaking the API.
Instead of 
```
cosmo = ccl.Cosmology(
Omega_c=0.25,
Omega_b=0.05,
h=0.7,
A_s=2.1e-9,
n_s=0.96,
mu_0=0.1, sigma_0=0.2,
)
```
the new API is now
```
from pyccl.modified_gravity import MuSigmaMG
cosmo = ccl.Cosmology(
Omega_c=0.25,
Omega_b=0.05,
h=0.7,
A_s=2.1e-9,
n_s=0.96,
mg_parametrisation=MuSigmaMG(mu_0=0.1, sigma_0=0.2),
)
```
This doesn't use `CCLNamedClass` at the moment due to a conflict with `dataclass` (see #1118).
> Container for MG params

- pyccl/_core/parameters/cosmology_params.py
- pyccl/ccl_core.i
- src/ccl_core.c
This is a quick fix for the aborts reported in #1129 by moving the call to disable the GSL error handling from `ccl_parameters_create` to `ccl_cosmology_create`. 
This uncovered a bunch of other issues though. From the python side, `ccl_parameters_create` isn't being used any more.
It is still used from within the C code though, mainly in halofit and the mu-Sigma MG stuff. So now there are two places in the code that deal with the non-trivial aspects of the `ccl_parameters` struct, namely the allocation of the massive neutrino arrays and MG arrays.
Speaking of these arrays, right now you can do some pretty nasty stuff by accessing arbitrary memory because `N_nu_mass` can be changed from python. I added a fix for one memory leak but there might be others.
```python
import pyccl as ccl …
```
> Fix GSL integration abort

- benchmarks/test_pk_4pt.py
- pyccl/halos/pk_4pt.py
- pyccl/tests/test_tkk2h.py
- pyccl/tests/test_tkkcNG.py
> Trispectrum docstring fix

- pyccl/power.py
Window function that is defined in docstring was incorrect (Factor of 3 within brackets instead of outside).  The window function actually used in the code is fine as far as I can tell.
> typo in docstring

- .github/environment.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- CMakeLists.txt
- benchmarks/test_ptpk_bacco_lbias.py
- pyccl/halos/halo_model.py
- pyccl/numpy.i
- pyccl/tests/test_pyutils.py
- pyproject.toml
- setup.py
Our latest releases haven't been pushed to pypi and conda because the automatic versioning was not working. This was broken in #1144 
Unfortunately fully testing this will require us to publish a new release and see if it pulls through. Hopefully we only need to do this once.
Closes #1207
Closes #1204
> Fix dynamic versioning

- pyccl/_nonlimber_FKEM.py
- pyccl/cells.py
- pyccl/tests/test_cells.py
Some of the hard-coded values used by FKEM lead to unstable power spectra in specific situations. This is documented in #1151 . This PR makes these parameters visible to users, so they can be tuned to the specific radial kernels being integrated.
To test that this solves the issue, I have added a unit test based on the example in  #1151 that failed with the default FKEM params.
Closes #1151
> Fexible non-Limber parameters

- benchmarks/test_ptpk.py
- pyccl/_nonlimber_FKEM.py
- pyccl/baryons/baccoemu_baryons.py
- pyccl/ccl.i
- pyccl/cells.py
- pyccl/errors.py
- pyccl/halos/pk_4pt.py
- pyccl/halos/profiles/ia.py
- pyccl/nl_pt/ept.py
- pyccl/pk2d.py
- pyccl/tests/test_cclerror.py
- pyccl/tests/test_cosmology_parameters.py
- pyccl/tests/test_ept_power.py
- pyccl/tests/test_pk2d.py
- pyccl/tests/test_tkk1h.py
- pyccl/tests/test_tracers.py
- pyccl/tracers.py
- readthedocs/api/pyccl.halos.hmfunc.nishimichi19.rst
- readthedocs/api/pyccl.halos.hmfunc.rst
- src/ccl_error.c
CCL often throws warnings about things that are relatively benign and should not plague the output of e.g. MCMC runs. This PR implements a granular way to control the verbosity of the warning messages thrown by CCL.
It uses some code by @nikfilippas .
While doing this I fixed a couple of bugs in the documentation.
Most of the changes are cosmetic. Anyone reviewing should start by looking at the changes in `error.py` (the rest is boilerplate)
> Warnings verbosity

- pyccl/halos/pk_4pt.py
- pyccl/tests/test_tkk_separable_growth.py
A large bottleneck in the computation time of covariances is the calculation of isotropized power spectra. The current implementation calculates this at each scale factor considered in the computation. By separating the growth factor from this computation, one can save computation time and maintain accuracy to a good approximation. 
The implementation includes optional flags when calculating the 2h_22, 3h, and 4h Trispectrum terms in `pk_4pt.py` and the corresponding functions for wrappers.
> Allow Separable Growth Functions to compute Isotropized Power Spectra

- .github/workflows/ci.yml
- pyccl/halos/profiles_2pt.py
- pyccl/tests/test_profiles.py
This PR allows for cross-correlations with different HOD profiles. In the case in which the profiles are different, the code reverts to the usual Fourier-space two-point moment as implemented in Profile2pt. This holds under the assumption that the two tracers are disjoint.
> Allowing for cross-correlations in HOD power spectrum.

- pyccl/halos/pk_4pt.py
There existed an issue of the amplitude of the trispectrum for the case of `matter, matter, HOD, matter` (found by Davide Sciotti), giving way too large values for the trispectrum in that case.  
Reason: `_get_norms` assigned a wrong norm in this case. In particular, the code asks if profile_1 and profile_4 are the same but assigns norm_4 to norm_3 instead of norm_1. Due to the structure of the `matter, matter, HOD, matter`, this would assign the HOD norm twice in this case.
After the fix, the amplitudes of the trispectra are consistent.
> fixing normalisation issue of trispectrum in halomodel
