LSSTDESC/CCL

src/ccl_power.c
Small edit in ccl_power.c to pass T_CMB from CCL to CLASS.
Addresses #311
=> passing T_cmb to CLASS

README.md
In response to issue #322
Note that the 'Known installation issues' part was moved after the Python installation instructions.
=> Update installation issues in README.md

tests/Distance Calculations Example.ipynb, tests/Lensing angular power spectrum.ipynb, tests/MCMC Likelihood Analysis.ipynb, tests/Photo-z example.ipynb, tests/Power spectrum example.ipynb
The ipython notebooks were incompatible with python3. Print statements now have parentheses.
=> print statements now have brackets

README.md, tests/ccl_sample_run.c
This is a minor update of the README, plus a small fix in a print statement of in ccl_sample_run
=> Update README to reflect current ccl_sample_run

src/ccl_cls.c, tests/ccl_test_cls.c
This addresses part of issue #347 , related to the factors of sqrt((l+2)!/(l-2)!) associated to the transfer functions of spin-2 quantities.
=> corrected spin-2 prefactors

include/fftlog.h, src/ccl_correlation.c, src/fftlog.c
Spare some additional sqrt() evaluations
=> simplified use of fftlog for correlation functions

tests/ccl_test_cmblens.c
=> Fixes re-setting of spline parameters in ccl_test_cmblens.c

tests/ccl_test_cmblens.c
I tracked down the reason why we couldn't get a better agreement with the benchmark for the CMB lensing power spectrum. This was due to the fact that the number of relativistic neutrinos wasn't set to 0 explicitly. Once this is done the agreement is almost at the level of 1E-4.
=> fixed CMB lensing test

CMakeLists.txt, README.md
This should solve #456 by adding an option to do a build in Debug and Release mode
=> Adds option to build CCL in debug mode

pyccl/__init__.py, pyccl/core.py, pyccl/errors.py, tests/ccl_test_power.py, tests/ccl_test_pyccl_interface.py
This PR adds a custom CCL error.
Closes #473
=> ENH add a custom CCLError

README.md, pyccl/__init__.py, pyccl/cls.py, tests/ccl_test_pyccl_interface.py
=> ENH simpler tracers

pyccl/cls.py
This PR updates the docs to properly specify which parameters are required or not.
Closes #512
=> DOC update docs for tracers

pyccl/ccl_redshifts.i, pyccl/redshifts.py, tests/ccl_test_pyccl_interface.py
OK  @c-d-leonard. I have fixed the issue. See the comment below.
=> BUG redshift functions

CHANGELOG.md, src/ccl_power.c
This PR evaluates the power spectrum near zero with class better. 
Closes #518
=> BUG eval power spectrum near zero better

CHANGELOG.md, src/ccl_power.c
This PR fixes the memory leak identified by @damonge in issues #547
=> BUG mem leak in power spectrum

CHANGELOG.md, src/fftlog.c
=> BUG fixed bug in fftlog for some complex arguments for v1.0

CHANGELOG.md, src/fftlog.c
This PR fixes the bug reported in #558 
Closes #558
=> BUG fixed bug in fftlog for some complex arguments

CHANGELOG.md, pyccl/cls.py, pyccl/core.py
This PR ensures we pass out an error message if C(ell) computations fail.
=> improved error reporting for C(ell)

pyccl/core.py, tests/ccl_test_core.py
This PR adds context managers. Closes #573
=> ENH add context managers

CHANGELOG.md, src/ccl_power.c, tests/ccl_test_bbks.c, tests/ccl_test_cls.c, tests/ccl_test_correlation.c, tests/ccl_test_massfunc.c, tests/ccl_test_sigmaM.c
=> fixed BBKS bug

CMakeLists.txt, include/ccl.h, include/ccl_halofit.h, src/ccl_background.c, src/ccl_class.c, src/ccl_halofit.c, src/ccl_power.c, tests/ccl_test_correlation_3d.c, tests/ccl_test_correlation_3dRSD.c, tests/ccl_test_power.py, tests/ccl_test_power_nu.c
This PR adds our own halofit.
Closes #599 
To do:
=> ENH adding our own halofit

CHANGELOG.md
=> Update CHANGELOG.md for halofit

CHANGELOG.md, src/ccl_power.c
=> Fix w_tophat expression

CHANGELOG.md, include/ccl_core.h, include/ccl_neutrinos.h, include/ccl_utils.h, pyccl/ccl_neutrinos.i, src/ccl_background.c, src/ccl_core.c, src/ccl_emu17.c, src/ccl_massfunc.c, src/ccl_neutrinos.c, src/ccl_power.c, src/ccl_utils.c
This PR removes all GSL accelerators so we can implement threading more easily. 
Closes #594
=> DEP remove all accelerators

src/ccl_massfunc.c
Addresses issue #536. Ready to review.
=> Added error for mass function when mass is out of range

pyccl/__init__.py, pyccl/halos/massdef.py, pyccl/massfunction.py, pyccl/pyutils.py, pyccl/tests/test_concentration.py, pyccl/tests/test_hbias.py, pyccl/tests/test_hmfunc.py, pyccl/tests/test_massfunction.py, readthedocs/api/pyccl.massfunction.rst, readthedocs/api/pyccl.rst
=> Bringing back old mass function functions for bckw compat.

README.md, readthedocs/source/installation.rst
=> Document lack of Windows support

include/ccl_f1d.h, pyccl/__init__.py, pyccl/ccl.i, pyccl/ccl_f1d.i, pyccl/pk2d.py, pyccl/pyutils.py, pyccl/tests/test_resampling.py, src/ccl_correlation.c, src/ccl_f1d.c, src/ccl_tracers.c
this implements a python-level routine to resample arrays through interpolation.
This is part of #704
=> Array resampling

.travis.yml
=> Travis to allow 2.7 failures for faster testing

.travis.yml, pyccl/ccl_tracers.i, pyccl/tests/test_swig_interface.py, pyccl/tests/test_tracers.py, pyccl/tracers.py
Closes #712 
Currently can return radial kernel. If @beckermr approves of this setup I'll implement transfer functions, ell-factors, and bessel derivative orders.
=> Return tracer functions

src/ccl_tracers.c
=> Parallel lensing kernel

include/ccl_utils.h, pyccl/ccl.i, pyccl/ccl_utils.i, pyccl/pyutils.py, pyccl/tests/test_spline_integ.py, src/ccl_cls.c, src/ccl_fftlog.c, src/ccl_utils.c
This PR:
* Paralelizes FFTLog.
* Paralelizes the spline integrator.
* Makes the latter accessible from python.
=> Two parallelized functions

CHANGELOG.md, include/ccl_neutrinos.h, pyccl/core.py, pyccl/neutrinos.py, pyccl/tests/test_neutrinos.py, pyccl/tests/test_parameters.py, src/ccl_neutrinos.c
quick pr to add a convenience option for a single massive neutrino. Tests have been modified to include this option; please let me know if you think we need more additional tests for this.
=> add single mass option for neutrinos

benchmarks/test_correlation.py, benchmarks/test_correlation_MG.py, pyccl/correlation.py, pyccl/tests/test_correlation.py
=> Correlation function doc fix

include/ccl_background.h, pyccl/ccl_background.i, pyccl/core.py, pyccl/tests/test_background.py, src/ccl_background.c
Adding keyword arguments, conditional expressions and initializing a C function.
=> First step to input distance

CHANGELOG.md, readthedocs/source/developer_installation.rst
This PR adds docs for a simple dev env.
Closes #772
cc @jablazek @c-d-leonard
=> DOC added dev install docs

pyccl/halos/hmfunc.py
=> Quick fix in mass function docstrings

pyccl/ccl_neutrinos.i, pyccl/neutrinos.py, src/ccl_neutrinos.c
Fix the issues described in Issue #780 where ccl.Omeganuh2 has unexpected behaviour.
=> Fix omeganuh2

.github/workflows/ci.yml, ci_scripts/install_class_linux.sh, ci_scripts/install_class_osx.sh
This PR moves the compilers back to conda like it was before.
=> REF use conda like we had it

src/ccl_tracers.c
A more conservative estimate of the kernel support. Addresses #865.
=> Fix estimation of kernel support.

pyccl/core.py, pyccl/pk2d.py, pyccl/tests/test_pk2d.py, pyccl/tests/test_power.py
=> Give useful error message when trying to pass decreasing a array to CalculatorCosmology

.github/workflows/ci.yml
=> Lint check before installing dependencies

.github/workflows/ci.yml, CHANGELOG.md, pyccl/tests/test_halofit_highz.py, src/ccl_halofit.c
This PR adds a fix and test for high-z halofit.
closes #907
=> TST add test for high-z halofit

pyccl/ccl_utils.i, pyccl/pyutils.py, pyccl/tests/test_tk3d.py, pyccl/tk3d.py
This PR implements the `Tk3D` equivalent of `Pk2D.get_spline_arrays`.
=> Allow access to Tk3D spline data

.github/workflows/publish.yml
Follow-up to #948 after checking that it works on test.pypi
=> Action to publish on pypi

pyccl/tracers.py
=> Spline check fix in tracers.py

pyccl/halos/profiles.py, pyccl/pk2d.py, pyccl/tests/test_profiles.py
The integration interpolation template should also be recalculated when `c500` changes.
=> `HaloProfileGNFW` bugfix for `c500` update.

.github/workflows/ci.yml
libomp was not found. Add one more LDFLAGS to fix the problem.
=> GitHub Actions: Fix class installation

pyccl/halos/profiles.py, pyccl/tests/test_profiles.py
* Remove unneeded code from last PR
* Fix free alpha dimension
* Update docstrings; Change default alpha to 'cosmo'
* Update docstrings for update_parameters
* Remove unneeded code
* Use np.full_like; Update tests
=> Fix free Einasto alpha dimension (#989)

pyccl/tests/test_cls.py
=> MG test fix

README.md, pyccl/correlations.py, readthedocs/api/pyccl.rst, readthedocs/source/installation.rst
This is a way to install PyCCL on Google Colab.
=> Doc install

benchmarks/test_covariances.py, pyccl/cells.py, pyccl/covariances.py, pyccl/tests/test_covariances.py, pyccl/tests/test_covs.py
=> Covariances in v3

pyccl/tests/test_tkk1h.py
Gets rid of a minor warning in tests.
=> Tkk1h warning test

pyccl/numpy.i
I introduced a bug in #1082 by using `sed` to search-replace. I'm amazed gha didn't pick it up.
This fixes it.
=> Bug from sed

CMakeLists.txt
=> Version number on CMakeLists.txt

include/ccl_massfunc.h, pyccl/halos/hmfunc/despali16.py, pyccl/halos/massdef.py, src/ccl_massfunc.c
=> Bugfix: wrong virial overdensity

.github/environment.yml, .github/workflows/ci.yml
classy is not compatible with Cython 3.0.0.
=> Fix classy installation

.github/environment.yml, .github/workflows/ci.yml, pyccl/tests/test_nonlin_camb_power.py
=> Use default `Neff` in test_nonlin_camb_power

pyccl/boltzmann.py
=> Outdated value of Neff in boltzmann.py

pyccl/covariances.py
=> Quick bugfix in `sigma2_B_from_mask`

pyccl/tests/test_tracers.py, pyccl/tracers.py
=> Throw error when initialising empty weak lensing or number counts tracer

benchmarks/test_hod.py, benchmarks/test_isw.py, pyccl/halos/halo_model.py
Just a small fix to how we use scipy's integrators to fix current deprecations.
=> Scipy deprecations

.github/environment.yml, pyccl/halos/profiles/ia.py
=> Scipy deprecation in halos/profiles/ia.py

.github/environment.yml, .github/workflows/ci.yml, pyccl/tests/test_hmfunc.py, pyproject.toml
Just a rehash of #1208. Thanks to @James11222 and @henryiii .
Closes #1180 
Closes #1205
=> Fixing build workflow

pyccl/halos/pk_4pt.py
=> Fixed issue #1214
